/**
 * useSandboxFileDownload Hook
 *
 * Downloads files generated by Anthropic's code execution sandbox.
 * Triggers browser download via blob URL + temporary <a> element.
 *
 * @module domains/files/hooks/useSandboxFileDownload
 */

import { useState, useCallback } from 'react';
import { getFileApiClient } from '@/src/infrastructure/api';

export interface UseSandboxFileDownloadReturn {
  /** Download a sandbox file by its Anthropic file ID */
  downloadSandboxFile: (fileId: string) => Promise<void>;
  /** File ID currently being downloaded (null if idle) */
  downloadingFileId: string | null;
  /** Error message if last download failed */
  error: string | null;
  /** Clear error state */
  clearError: () => void;
}

/**
 * Hook for downloading sandbox-generated files from Anthropic's Files API.
 *
 * @example
 * ```tsx
 * function SandboxFileBadge({ fileId }: { fileId: string }) {
 *   const { downloadSandboxFile, downloadingFileId, error } = useSandboxFileDownload();
 *   const isDownloading = downloadingFileId === fileId;
 *
 *   return (
 *     <button onClick={() => downloadSandboxFile(fileId)} disabled={isDownloading}>
 *       {isDownloading ? 'Downloading...' : 'Download'}
 *     </button>
 *   );
 * }
 * ```
 */
export function useSandboxFileDownload(): UseSandboxFileDownloadReturn {
  const [downloadingFileId, setDownloadingFileId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const clearError = useCallback(() => {
    setError(null);
  }, []);

  const downloadSandboxFile = useCallback(async (fileId: string): Promise<void> => {
    setDownloadingFileId(fileId);
    setError(null);

    try {
      const fileApi = getFileApiClient();
      const result = await fileApi.downloadSandboxFile(fileId);

      if (result.success) {
        const { blob, filename } = result.data;
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      } else {
        setError(result.error.message);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to download file';
      setError(message);
    } finally {
      setDownloadingFileId(null);
    }
  }, []);

  return {
    downloadSandboxFile,
    downloadingFileId,
    error,
    clearError,
  };
}
