/**
 * File Chunking Service
 *
 * Orchestrates the chunking of extracted text from files:
 * - Reads extracted_text from files with pipeline_status='chunking'
 * - Applies appropriate chunking strategy based on MIME type
 * - Inserts chunks into file_chunks table
 *
 * Embedding generation is handled by the pipeline (FileEmbedWorker),
 * which runs automatically after chunking via BullMQ Flow sequencing.
 *
 * @module services/files/FileChunkingService
 */

import { prisma } from '@/infrastructure/database/prisma';
import { createChildLogger } from '@/shared/utils/logger';
import { ChunkingStrategyFactory } from '../chunking/ChunkingStrategyFactory';
import type { ChunkingOptions } from '../chunking/types';
import type { FileChunkingJob } from '@/infrastructure/queue/types';

// Child logger for this service (uses createChildLogger for LOG_SERVICES filtering)
const logger = createChildLogger({ service: 'FileChunkingService' });

/**
 * Default chunking options
 * - 512 tokens max per chunk (optimal for embeddings)
 * - 50 token overlap for context continuity
 */
const DEFAULT_CHUNKING_OPTIONS: ChunkingOptions = {
  maxTokens: 512,
  overlapTokens: 50,
};

/**
 * Image MIME types that don't require text chunking
 * Images are handled differently - embeddings generated via Azure Computer Vision
 */
const IMAGE_MIME_TYPES = new Set([
  'image/jpeg',
  'image/png',
  'image/gif',
  'image/webp',
]);

/**
 * Result of chunking operation
 */
export interface ChunkingResult {
  fileId: string;
  chunkCount: number;
  totalTokens: number;
  embeddingJobId?: string;
}

/**
 * File data needed for chunking
 */
interface FileForChunking {
  id: string;
  userId: string;
  mimeType: string;
  extractedText: string | null;
  pipelineStatus: string;
}

/**
 * File Chunking Service Class
 *
 * Singleton service that chunks extracted text and prepares for embedding.
 */
export class FileChunkingService {
  private static instance: FileChunkingService | null = null;

  private constructor() {
    logger.info('FileChunkingService initialized');
  }

  /**
   * Get singleton instance
   */
  public static getInstance(): FileChunkingService {
    if (!FileChunkingService.instance) {
      FileChunkingService.instance = new FileChunkingService();
    }
    return FileChunkingService.instance;
  }

  /**
   * Reset singleton (for testing)
   */
  public static resetInstance(): void {
    FileChunkingService.instance = null;
  }

  /**
   * Process file chunks
   *
   * Main entry point called by MessageQueue worker.
   *
   * @param jobData - File chunking job data
   * @returns Chunking result
   */
  public async processFileChunks(jobData: FileChunkingJob): Promise<ChunkingResult> {
    const { fileId, userId, mimeType, sessionId } = jobData;

    logger.debug({
      fileId, userId, mimeType,
      mimeTypeType: typeof mimeType,
      mimeTypeValue: mimeType === null ? 'NULL' : mimeType === undefined ? 'UNDEFINED' : mimeType,
      isImageMime: IMAGE_MIME_TYPES.has(mimeType),
    }, '[TRACE] processFileChunks entry - mimeType from job data');

    logger.info({ fileId, userId, mimeType }, 'Starting file chunking');

    // Handle images separately - they don't have text to chunk
    // Image embeddings are generated by ImageProcessor and persisted by FileProcessingService
    // We need to index them in Azure AI Search for visual search
    if (IMAGE_MIME_TYPES.has(mimeType)) {
      logger.info(
        { fileId, userId, mimeType },
        'Handling image file - indexing embedding in Azure AI Search'
      );

      await this.indexImageEmbedding(fileId, userId, sessionId);

      return {
        fileId,
        chunkCount: 0,
        totalTokens: 0,
      };
    }

    // 1. Get file with extracted_text
    const file = await this.getFileForChunking(fileId, userId);

    if (!file) {
      throw new Error(`File not found: ${fileId}`);
    }

    if (!file.extractedText) {
      logger.warn({ fileId }, 'No extracted text found, skipping chunking');
      return {
        fileId,
        chunkCount: 0,
        totalTokens: 0,
      };
    }

    // 2. Validate processing status
    // In the pipeline (PRD-07), files are in 'chunking' status when this runs.
    if (file.pipelineStatus !== 'chunking') {
      throw new Error(`File not in chunking status: ${file.pipelineStatus}`);
    }

    try {
      // 4. Select chunking strategy based on MIME type
      const strategy = ChunkingStrategyFactory.createForFileType(mimeType, DEFAULT_CHUNKING_OPTIONS);

      // 5. Generate chunks
      const chunks = strategy.chunk(file.extractedText);

      logger.info({ fileId, chunkCount: chunks.length }, 'Generated chunks');

      // 6. Insert chunks into database
      const { getFileChunkRepository } = await import(
        '@/services/files/repository/FileChunkRepository'
      );
      const chunkRepo = getFileChunkRepository();
      await chunkRepo.createMany(fileId, userId, chunks);

      // 7. Calculate total tokens
      const totalTokens = chunks.reduce((sum, chunk) => sum + chunk.tokenCount, 0);

      // 8. Embedding is handled by the pipeline (BullMQ Flow).
      // The FileEmbedWorker processes the next stage automatically.
      // No explicit enqueue is needed here.
      const embeddingJobId: string | undefined = undefined;

      logger.info({
        fileId,
        chunkCount: chunks.length,
        totalTokens,
        embeddingJobId,
      }, 'File chunking completed successfully');

      return {
        fileId,
        chunkCount: chunks.length,
        totalTokens,
        embeddingJobId,
      };
    } catch (error) {
      throw error;
    }
  }

  /**
   * Get file data for chunking
   *
   * @param fileId - File ID
   * @param userId - User ID (for multi-tenant isolation)
   * @returns File data or null if not found
   */
  private async getFileForChunking(fileId: string, userId: string): Promise<FileForChunking | null> {
    const row = await prisma.files.findFirst({
      where: { id: fileId, user_id: userId },
      select: {
        id: true,
        user_id: true,
        mime_type: true,
        extracted_text: true,
        pipeline_status: true,
      },
    });

    if (!row) {
      return null;
    }

    return {
      id: row.id,
      userId: row.user_id,
      mimeType: row.mime_type,
      extractedText: row.extracted_text,
      pipelineStatus: row.pipeline_status,
    };
  }

  /**
   * Index image embedding in Azure AI Search
   *
   * Retrieves the embedding from ImageEmbeddingRepository and indexes it
   * in Azure AI Search for visual search capability. Also passes AI-generated caption for improved search relevance.
   * Emits WebSocket event to notify frontend of readiness state change.
   *
   * @param fileId - File ID
   * @param userId - User ID
   * @param sessionId - Session ID for WebSocket room targeting (optional)
   */
  private async indexImageEmbedding(fileId: string, userId: string, sessionId?: string): Promise<void> {
    try {
      const { getImageEmbeddingRepository } = await import(
        '@/repositories/ImageEmbeddingRepository'
      );
      const repository = getImageEmbeddingRepository();
      const embeddingRecord = await repository.getByFileId(fileId, userId);

      if (!embeddingRecord) {
        logger.warn({ fileId, userId }, 'No image embedding found - skipping indexing');

        // Emit readiness_changed event even when no embedding (file is still "ready")
        await this.emitReadinessChanged(fileId, userId, sessionId);
        return;
      }

      // Get file name, mime_type, file_modified_at, size_bytes, and source metadata
      const { getFileRepository } = await import(
        '@/services/files/repository/FileRepository'
      );
      const fileRepo = getFileRepository();
      const fileMeta = await fileRepo.getFileWithScopeMetadata(fileId, userId);

      const fileName = fileMeta?.name || 'unknown.jpg';
      const fileMimeType = fileMeta?.mime_type ?? undefined;
      const fileModifiedAtRaw = fileMeta?.file_modified_at;
      const fileModifiedAt = fileModifiedAtRaw ? fileModifiedAtRaw.toISOString() : undefined;
      const sizeBytes = fileMeta?.size_bytes ?? undefined;
      const imageSiteId = fileMeta?.scope_site_id ?? undefined;
      const imageSourceType = fileMeta?.source_type ?? 'local';
      const imageParentFolderId = fileMeta?.parent_folder_id ?? undefined;

      logger.debug({
        fileId, userId,
        dbMimeType: fileMeta?.mime_type,
        dbMimeTypeType: typeof fileMeta?.mime_type,
        resolvedMimeType: fileMimeType,
        resolvedMimeTypeType: typeof fileMimeType,
        dbRecordFound: !!fileMeta,
      }, '[TRACE] indexImageEmbedding - mimeType from DB re-read (image path)');

      // Generate text embedding from caption for contentVector search path.
      // PRD-202: Skip when unified index is enabled — the unified embeddingVector field
      // replaces both contentVector and imageVector, so a separate captionContentVector
      // is not needed and would reference a different vector space (legacy OpenAI).
      let captionContentVector: number[] | undefined;
      const { isUnifiedIndexEnabled } = await import(
        '@/services/search/embeddings/EmbeddingServiceFactory'
      );
      if (!isUnifiedIndexEnabled() && embeddingRecord.caption) {
        // Legacy: generate captionContentVector for contentVector field
        // (unified index uses single embeddingVector — no separate captionContentVector needed)
        try {
          const { EmbeddingService } = await import('@/services/embeddings/EmbeddingService');
          const embeddingService = EmbeddingService.getInstance();
          logger.info(
            { fileId, userId, captionLength: embeddingRecord.caption.length },
            'Generating contentVector from caption'
          );
          const captionEmbedding = await embeddingService.generateTextEmbedding(
            embeddingRecord.caption, userId, fileId
          );
          captionContentVector = captionEmbedding.embedding;
          logger.info(
            { fileId, userId, dimensions: captionContentVector.length },
            'contentVector generated successfully from caption'
          );
        } catch (error) {
          // Non-fatal: image still findable via imageVector and Semantic Ranker
          const errorInfo = error instanceof Error
            ? { message: error.message, name: error.name, stack: error.stack?.split('\n').slice(0, 3).join(' | ') }
            : { value: String(error) };
          logger.error(
            {
              error: errorInfo,
              fileId,
              userId,
              captionLength: embeddingRecord.caption.length,
              captionPreview: embeddingRecord.caption.substring(0, 80),
            },
            'FAILED to generate contentVector from caption - image missing from hybrid text search'
          );
        }
      } else if (!isUnifiedIndexEnabled()) {
        logger.warn(
          { fileId, userId },
          'No caption available for contentVector generation'
        );
      } else {
        logger.debug(
          { fileId, userId },
          'Unified index enabled — skipping captionContentVector generation (embeddingVector covers both text and image)'
        );
      }

      // Index in Azure AI Search
      const { VectorSearchService } = await import('@services/search/VectorSearchService');
      const vectorSearchService = VectorSearchService.getInstance();

      logger.debug({
        fileId, userId,
        mimeTypePassedToVSS: fileMimeType,
        mimeTypePassedToVSSType: typeof fileMimeType,
        hasCaption: !!embeddingRecord.caption,
        hasCaptionContentVector: !!captionContentVector,
      }, '[TRACE] indexImageEmbedding - about to call VectorSearchService.indexImageEmbedding');

      await vectorSearchService.indexImageEmbedding({
        fileId,
        userId,
        embedding: embeddingRecord.embedding,
        fileName,
        caption: embeddingRecord.caption ?? undefined,
        mimeType: fileMimeType,
        contentVector: captionContentVector,
        fileModifiedAt,
        sizeBytes,
        siteId: imageSiteId,
        sourceType: imageSourceType,
        parentFolderId: imageParentFolderId,
      });

      logger.info(
        {
          fileId,
          userId,
          dimensions: embeddingRecord.embedding.length,
          hasCaption: !!embeddingRecord.caption,
        },
        'Image embedding indexed in Azure AI Search successfully'
      );

      // Emit WebSocket event to notify frontend
      await this.emitReadinessChanged(fileId, userId, sessionId);
    } catch (error) {
      logger.error(
        {
          error: error instanceof Error ? error.message : String(error),
          fileId,
          userId,
        },
        'Failed to index image embedding'
      );

      throw error;
    }
  }

  /**
   * Emit readiness_changed WebSocket event
   *
   * Notifies frontend that file is ready for use (processing + embedding completed).
   *
   * @param fileId - File ID
   * @param userId - User ID
   * @param sessionId - Session ID for WebSocket room targeting
   */
  private async emitReadinessChanged(fileId: string, userId: string, sessionId?: string): Promise<void> {
    try {
      const { getFileEventEmitter } = await import('@/domains/files/emission/FileEventEmitter');
      const { FILE_READINESS_STATE } = await import('@bc-agent/shared');

      const eventEmitter = getFileEventEmitter();

      eventEmitter.emitReadinessChanged(
        { fileId, userId, sessionId },
        {
          previousState: FILE_READINESS_STATE.PROCESSING,
          newState: FILE_READINESS_STATE.READY,
        }
      );

      logger.debug({ fileId, userId, sessionId: !!sessionId }, 'Emitted readiness_changed event');
    } catch (error) {
      // Don't fail the operation if event emission fails
      logger.warn(
        {
          error: error instanceof Error ? error.message : String(error),
          fileId,
          userId,
        },
        'Failed to emit readiness_changed event - file processing still succeeded'
      );
    }
  }

}

/**
 * Get FileChunkingService singleton
 */
export function getFileChunkingService(): FileChunkingService {
  return FileChunkingService.getInstance();
}
