/**
 * Sandbox File Download Routes
 *
 * Proxy endpoint for downloading files generated by Anthropic's
 * code execution sandbox (bash_code_execution tool).
 *
 * These files are ephemeral — they auto-expire on Anthropic's side.
 * The backend acts as a pass-through proxy (no Azure Blob persistence).
 *
 * @module routes/files/sandbox-download.routes
 */

import { Router, Request, Response } from 'express';
import { authenticateMicrosoft } from '@/domains/auth/middleware/auth-oauth';
import { getAnthropicFilesService } from '@services/files/AnthropicFilesService';
import { sendError } from '@/shared/utils/error-response';
import { ErrorCode } from '@/shared/constants/errors';
import { createChildLogger } from '@/shared/utils/logger';
import { getUserId } from './helpers';
import { anthropicFileIdSchema } from './schemas/file.schemas';

const logger = createChildLogger({ service: 'SandboxDownloadRoutes' });
const router = Router();

/**
 * GET /api/files/sandbox/:fileId/download
 *
 * Proxy-download a sandbox-generated file from Anthropic's Files API.
 * Returns the file content with appropriate Content-Type and Content-Disposition headers.
 *
 * Error responses:
 * - 400: Invalid file ID format
 * - 400: File is not downloadable
 * - 401: Not authenticated
 * - 410: File has expired on Anthropic's side
 * - 500: Internal error
 */
router.get(
  '/sandbox/:fileId/download',
  authenticateMicrosoft,
  async (req: Request, res: Response): Promise<void> => {
    try {
      const userId = getUserId(req);

      // Validate file ID format
      const validation = anthropicFileIdSchema.safeParse(req.params);
      if (!validation.success) {
        sendError(res, ErrorCode.VALIDATION_ERROR, 'Invalid Anthropic file ID format');
        return;
      }

      const { fileId } = validation.data;

      logger.info({ userId, fileId }, 'Downloading sandbox file');

      const anthropicFiles = getAnthropicFilesService();

      // Get metadata first to check downloadable status and get filename/mime
      const metadata = await anthropicFiles.getFileMetadata(fileId);

      if (!metadata.downloadable) {
        logger.warn({ userId, fileId }, 'Sandbox file is not downloadable');
        sendError(res, ErrorCode.BAD_REQUEST, 'File is not available for download');
        return;
      }

      // Download the file content
      const buffer = await anthropicFiles.downloadSandboxFile(fileId);

      logger.info(
        { userId, fileId, filename: metadata.filename, size: buffer.length },
        'Sandbox file downloaded successfully'
      );

      // Set response headers
      res.setHeader('Content-Type', metadata.mimeType);

      const encodedFilename = encodeURIComponent(metadata.filename)
        .replace(/['()]/g, escape)
        .replace(/\*/g, '%2A');
      res.setHeader(
        'Content-Disposition',
        `attachment; filename="${metadata.filename}"; filename*=UTF-8''${encodedFilename}`
      );
      res.setHeader('Content-Length', buffer.length.toString());

      res.send(buffer);
    } catch (error) {
      const errorInfo =
        error instanceof Error
          ? { message: error.message, name: error.name, stack: error.stack }
          : { value: String(error) };

      logger.error(
        { error: errorInfo, userId: req.userId, fileId: req.params.fileId },
        'Sandbox file download failed'
      );

      if (error instanceof Error && error.message === 'User not authenticated') {
        sendError(res, ErrorCode.UNAUTHORIZED, 'User not authenticated');
        return;
      }

      // Anthropic returns 404 when sandbox files have expired
      if (
        error instanceof Error &&
        ('status' in error && (error as Record<string, unknown>).status === 404)
      ) {
        sendError(res, ErrorCode.EXPIRED, 'This sandbox file has expired and is no longer available');
        return;
      }

      sendError(res, ErrorCode.INTERNAL_ERROR, 'Failed to download sandbox file');
    }
  }
);

/**
 * GET /api/files/sandbox/:fileId/metadata
 *
 * Retrieve metadata for a sandbox-generated file from Anthropic's Files API.
 * Returns filename, MIME type, and size without downloading the file content.
 *
 * Error responses:
 * - 400: Invalid file ID format
 * - 401: Not authenticated
 * - 410: File has expired on Anthropic's side
 * - 500: Internal error
 */
router.get(
  '/sandbox/:fileId/metadata',
  authenticateMicrosoft,
  async (req: Request, res: Response): Promise<void> => {
    try {
      const userId = getUserId(req);

      const validation = anthropicFileIdSchema.safeParse(req.params);
      if (!validation.success) {
        sendError(res, ErrorCode.VALIDATION_ERROR, 'Invalid Anthropic file ID format');
        return;
      }

      const { fileId } = validation.data;

      logger.info({ userId, fileId }, 'Fetching sandbox file metadata');

      const anthropicFiles = getAnthropicFilesService();
      const metadata = await anthropicFiles.getFileMetadata(fileId);

      res.json({
        filename: metadata.filename,
        mimeType: metadata.mimeType,
        sizeBytes: metadata.sizeBytes,
      });
    } catch (error) {
      const errorInfo =
        error instanceof Error
          ? { message: error.message, name: error.name, stack: error.stack }
          : { value: String(error) };

      logger.error(
        { error: errorInfo, userId: req.userId, fileId: req.params.fileId },
        'Sandbox file metadata fetch failed'
      );

      if (error instanceof Error && error.message === 'User not authenticated') {
        sendError(res, ErrorCode.UNAUTHORIZED, 'User not authenticated');
        return;
      }

      if (
        error instanceof Error &&
        ('status' in error && (error as Record<string, unknown>).status === 404)
      ) {
        sendError(res, ErrorCode.EXPIRED, 'This sandbox file has expired and is no longer available');
        return;
      }

      sendError(res, ErrorCode.INTERNAL_ERROR, 'Failed to retrieve sandbox file metadata');
    }
  }
);

export default router;
